version: 2.1

executors:
  gcloud-executor:
    docker:
      - image: cimg/base:2023.03  # More lightweight base image
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: gcloud-executor
    steps:
      - checkout

  setup_gcloud:
    executor: gcloud-executor
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            curl -sSL https://sdk.cloud.google.com | bash
            echo 'source ~/.bashrc' >> $BASH_ENV
      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCLOUD_SERVICE_KEY" | base64 --decode > gcp-key.json
            gcloud auth activate-service-account --key-file=gcp-key.json --quiet
            gcloud config set project $GOOGLE_PROJECT_ID

  build_docker_image:
    executor: gcloud-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com | sh
      - run:
          name: Authenticate with Google Container Registry
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - run:
          name: Build and Push Image
          command: |
            docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:latest .
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/llmops-repo/llmops-app:latest

  deploy_to_gke:
    executor: gcloud-executor
    steps:
      - checkout
      - run:
          name: Install kubectl and gke-gcloud-auth-plugin
          command: |
            gcloud components install kubectl gke-gcloud-auth-plugin --quiet
      - run:
          name: Configure GKE Access
          command: |
            gcloud container clusters get-credentials $GKE_CLUSTER \
              --region $GOOGLE_COMPUTE_REGION \
              --project $GOOGLE_PROJECT_ID
      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f kubernetes-deployment.yaml
            kubectl rollout status deployment/celebmind-app --timeout=3m

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout_code
      - setup_gcloud:
          requires:
            - checkout_code
      - build_docker_image:
          requires:
            - setup_gcloud
      - deploy_to_gke:
          requires:
            - build_docker_image